version: '2'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/app
        depends_on:
            - elasticsearch
        environment:
            ES_HOST: elasticsearch
            ES_PORT: 9200
    elasticsearch:
        image: elasticsearch:7.5.1
        environment:
            - discovery.type=single-node
        ports:
            - "9200:9200"
            - "9300:9300"